FROM plexinc/pms-docker:latest

# Labels
LABEL maintainers="Francesco Sodano"
LABEL project="AZPlex"

# Install wget, git, apt-utils
RUN apt-get update && apt-get -y install \
    apt-utils \
    wget \
    git

# Install blobfuse
RUN wget https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb && \
    dpkg -i packages-microsoft-prod.deb && \
    apt-get update && \
    apt-get -y install blobfuse fuse && \
    mkdir -p /blobfuse/tmp

# Cleanup
RUN apt-get remove -y wget \
    apt-get -y autoremove && \
    apt-get -y clean && \
    rm -rf /var/lib/apt/lists/* && \
    rm -rf /tmp/* && \
    rm -rf /var/tmp/*
